# Generated by Django 4.1.3 on 2022-12-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_id', models.IntegerField()),
                ('p_name', models.CharField(max_length=60)),
                ('p_price', models.IntegerField()),
                ('p_img_src', models.CharField(max_length=60)),
            ],
        ),
    ]
